---
title: "Untitled"
author: "Anders Swanson"
date: "12/29/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE}
library(tidyverse)
library(httr)
library(lubridate)
library(ggplot2)

KEY <- read_lines("keyfile.txt")
```

```{r}
getData <- function(YEAR) {
    START <- paste0(as.character(YEAR),
                        "-01-01")
    END <- paste0(as.character(YEAR+1),
                    "-01-01")
    
    cxn <- GET("https://www.rescuetime.com/anapi/data",
           query = list(
               key = KEY,
               format = "csv",
               perspective = "interval",
               resolution_time = "week",
               restrict_begin = START,
               restrict_end = END,
               restrict_activity = ""
           ))
    print(http_status(cxn)$message)
    
    content(cxn)
}

df_13 <- getData(2013)
df_14 <- getData(2014)
df_15 <- getData(2015)
df_16 <- getData(2016)
df_17 <- getData(2017)
```

```{r}
df_raw <- content(cxn) %>%
    select(-`Number of People`) %>%
    arrange(Date) %>%
    mutate(Duration = dseconds(`Time Spent (seconds)`),
           Hours = `Time Spent (seconds)`/(60*60))
```

```{r}
head(df)
```

```{r}
plot <- df %>%
    ggplot(aes(x = Hours)) +
    geom_bar() +
    facet_wrap(~Category)
plot
```

```{r}
plot <- df %>%
    ggplot(aes(Activity, Hours)) +
    geom_bar(stat = "identity")
plot
```

```{r}
df_sum <- df_raw %>%
    group_by(Activity) %>%
    summarise(TotalHours = sum(Hours)) %>%
    top_n(20, TotalHours) %>%
    arrange(-TotalHours) %>%
    ungroup() %>%
    mutate(Activity = factor(Activity,
                         levels = df_sum$Activity[order(df_sum$TotalHours)]))

# data$carb <- factor(data$carb, levels = data$carb[order(-data$mpg)])
plot <- df_sum %>%
    ggplot(aes(Activity, TotalHours)) +
    # ggplot(aes(reorder(Activity, -table(Activity)[Activity]), TotalHours)) +
    geom_bar(stat = "identity") +
    # scale_x_discrete(limits = positions)
    coord_flip()
plot
```

```{r}

```

